export const FETCH_INFO = 'fetch_info'
export const ADD_INFO = 'add_info'
export const DELETE_INFO = 'delete_info'
export const EDIT_INFO = 'edit_info'
export const UPDATE_INFO = 'update_info'
export const PRICEFILTER_INFO = 'filter_by_price_info'
export const DATEFILTER_INFO = 'filter_by_date_info'
export const ROOMFILTER_INFO = 'filter_by_room_info'